#!/bin/bash

SPACK_VERSION=v1.2.1
GCC_VERSION=14
CUDA_ARCH=80

# Should be little reason to mess with anything below here

GCC_VERSION_UPSTREAM=$(rpm -q --queryformat '%{VERSION}' gcc)
LIBEVENT_VERSION_UPSTREAM=$(rpm -q --queryformat '%{VERSION}' libevent-devel)
PMIX_VERSION_UPSTREAM=$(rpm -q --queryformat '%{VERSION}' pmix-ohpc)
SLURM_VERSION_UPSTREAM=$(rpm -q --queryformat '%{VERSION}' slurm-ohpc)

SPACK_TARBALL=spack-$(echo ${SPACK_VERSION} | sed 's/^v//g').tar.gz
if [ ! -f ${SPACK_TARBALL} ]; then
    echo "### Grabbing ${SPACK_TARBALL}"
    curl -LO https://github.com/spack/spack/releases/download/${SPACK_VERSION}/${SPACK_TARBALL}
else
    echo "### ${SPACK_TARBALL} already exists, not downloading again"
fi

SPACK_HOME=$(realpath ${SPACK_VERSION})
if [ ! -e ${SPACK_HOME} ]; then
    echo "### ${SPACK_HOME} did not exist, making directory and extracting ${SPACK_TARBALL} into it"
    mkdir -p ${SPACK_HOME}
    tar --strip-components=1 -C ${SPACK_HOME} -xf spack-1.2.1.tar.gz
elif [ -f ${SPACK_HOME}/share/spack/setup-env.sh ]; then
    echo "### ${SPACK_HOME} does not appear to be a Spack directory, bailing out"
    exit 1
else
    echo "### ${SPACK_HOME} exists, but was not a directory, bailing out"
    exit 1
fi

echo "### Updating site settings"
cd site-settings
for y in *.yaml; do
    DEST=${SPACK_HOME}/etc/spack/site/$y
    if [ -f ${DEST} ]; then
        echo "${DEST} already exists, not overwriting"
    else
        /bin/cp $y ${DEST}
        perl -pi.bak -e "
            s/__CUDA_ARCH__/${CUDA_ARCH}/g;
            s/__GCC_VERSION__/${GCC_VERSION}/g;
            s/__GCC_VERSION_UPSTREAM__/${GCC_VERSION_UPSTREAM}/g;
            s/__LIBEVENT_VERSION_UPSTREAM__/${LIBEVENT_VERSION_UPSTREAM}/g;
            s/__PMIX_VERSION_UPSTREAM__/${PMIX_VERSION_UPSTREAM}/g;
            s/__SLURM_VERSION_UPSTREAM__/${SLURM_VERSION_UPSTREAM}/g;
            " \
            ${DEST} 
    fi
done
cd ..
echo "### Adding OS-provided compilers to site settings"
. ${SPACK_HOME}/share/spack/setup-env.sh
spack compiler find --scope=site
